apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bookshop-order-service
  name: bookshop-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshop-order-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bookshop-order-service
    spec:
      containers:
      - image: ghcr.io/bladespring/bookshop-order-service:0.0.1
        name: bookshop-order-service
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
        resources: {}
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://bookshop-postgres/bookshopdb_order
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://bookshop-config-service
          - name: SPRING_PROFILES_ACTIVE
            value: prod
status: {}
