apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bookshop-order-service
  name: bookshop-order-service
spec:
  ports:
  - name: 80-9001
    port: 80
    protocol: TCP
    targetPort: 9001
  selector:
    app: bookshop-order-service
  type: ClusterIP
status:
  loadBalancer: {}
